\input texinfo @c -*-texinfo-*-
@comment %**start of header
@setfilename TextMidiFormEdit.info
@settitle TextMidiFormEdit
@documentencoding US-ASCII
@exampleindent asis
@comment %**end-of-header

@dircategory music
@direntry
* TextMidiFormEdit: (TextMidiFormEdit.info). Edit a form file for textmidicgm to use.
@end direntry

@comment @documentlanguage en_US

@titlepage
@title Using @command{TextMidiFormEdit}
@subtitle The textmidicgm form editor
@author Thomas E. Janzen
@end titlepage
@copying
Copyright @copyright{} 2024 Thomas E. Janzen.
@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2
or any later version published by the Free Software Foundation; with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the
license is included in the section entitled ``GNU Free Documentation License.''
@end quotation
@end copying
@insertcopying

@ifnottex
@node Top
@top TextMidiFormEdit

@end ifnottex
@contents

@menu
* Overview::
* Downloading TextMidiFormEdit::
* Invoking TextMidiFormEdit::
* Musical Form Window::
* Instrumental Voices Window::
* Form Plot Window::
* Keyboard Window::
* GNU Free Documentation License::
* Bibliography::
* Concept Index::
@end menu
@node Overview
@chapter Overview
@cindex overview
The @command{TextMidiFormEdit} program can be used interactively to
edit new or pre-existing musical form files used by textmidicgm,
which generates works of music in textmidi language,
which can then be converted by @command{textmidi} into standard MIDI 1.1 file formats.
Using @command{TextMidiFormEdit}, it is possible to edit musical forms
as defined by @command{textmidicgm} rather than hand-edit the XML form file.

The model of musical form defined by textmidicgm is described in
the info file for textmidicgm.  This manual only describes the
user interface for TextMidiFormEdit.py.

@menu
* What is TextMidiFormEdit?::
@end menu

@node What is TextMidiFormEdit?
@section What is TextMidiFormEdit?
@cindex TextMidiFormEdit
The program @command{TextMidiFormEdit} can be used interactively to
create new musical form files, or edit previously-existing 
musical form files, as used by @command{textmidicgm}.

@node Downloading TextMidiFormEdit
@chapter Downloading TextMidiFormEdit
@cindex Downloading TextMidiFormEdit
If you have downloaded TextMidiFormEdit.py and its support *.py files, then
you can run it as described below.
You can also download TextMidiFormEdit from pypi.org.
@smallexample
python3 -m pip install --no-deps TextMidiFormEdit
@end smallexample
@node Invoking TextMidiFormEdit
@chapter Invoking TextMidiFormEdit
@cindex Invoking TextMidiFormEdit
@command{TextMidiFormEdit.py} has no options.  To run it, go to the directory
where it is found (after unpacking the archive for TextMIDITools) and invoke it:
@smallexample
./TextMidiFormEdit.py
@end smallexample
You may specify a form file to be edited on the command line:
@smallexample
./TextMidiFormEdit.py symphony.xml
@end smallexample
or open a form file using the menus.

If you downloaded TextMidiFormEdit from pypi.org, or installed it in an equivalent way,
you can use it as a python package:
@smallexample
python3
>>> from TextMidiFormEdit import *
>>> TextMidiFormEdit()
@end smallexample
When you quit the application, just exit from python with control-D or 
@smallexample
>>> exit()
@end smallexample
@node Musical Form Window
@chapter Musical Form Window
@cindex Musical Form Window
@image{MusicalFormWindow,5.7in,6.25in,Musical Form Window, png}
The Musical Form window allows the setting of global form
qualities except for the instrumental attributes of individual
voices, which is done on the Voices window.
@menu
* Name::
* Copyright::
* Len::
* Min/Max Note Len::
* Pulse/Sec::
* Ticks per Quarter::
* Beat Size::
* Meter::
* Tempo per Beat::
* Melodic Probabilities::
* Arrangements::
* Scale Transpose and From Keyboard::
* Pitch Form::
* Rhythm Form::
* Dynamic Form::
* Texture Form::
@end menu
The Musical Form Window has several items.
@node Name
@section Name
@cindex Name
The name string can be typed in; it is meant to be the title of the musical
work to be created by textmidicgm.
@node Copyright
@section Copyright
@cindex Copyright
The copyright string can be typed in.
It is not copied to the MIDI file that is created from the form file
by @command{textmidicgm}.
@node Len
@section Len
@cindex Len
The len text field is the duration of the musical work in seconds.
Entering 600 will tell textmidicgm to generate 10 minutes of music.
@node Min/Max Note Len
@section Min/Max Note Len
@cindex Min/Max Note Len
The minimum and maximum note lengths specifies the duration range for all note events.
When the rhythm curve is very low and the range curve narrow, the min note length is used;
when the rhythm curve is high with a narrow range, the maximum note length is used.
@node Pulse/Sec
@section Pulse/Sec
@cindex Pulse/Sec
Pulse per second is used optionally to force textmidicgm to generate rhythms that line up on
a pulse.  Such music is likely to be easier to notate in scoring program such that human players 
could play it.  Note, however, that textmidicgm has no model of meter, that is, the grouping of
beats and accents.  The original concept for this model of form (develoiped in 1976 for manual
composition) was connected to very fluid, conversational, ametrical rhythms.
On the other hand, setting a pulse can make works produced by textmidicgm sound more dance-like,
for example, with a pulse of about 5 or so per second.
@node Ticks per Quarter
@section Ticks per Quarter
@cindex Ticks per Quarter
The musical time values of ticks/quarter, beat size, meter and tempo per beat are 
conveniences that specify how the @command{textmidi} language file is to be written.
They do not, in principle, add to the capability of @command{textmidicgm}.
Ticks per quarter is required by the MIDI spec and may be a convenient value.  It could be
as low as 24, is often 240, but can be a higher value such as 720.  It may be helpful to
have a factor-rich value for ticks/quarter so that divisions such as triplets,
quintuplets, and the usual divisions of 2 can be exact.  For example, 720 is the product of
2*2*2*2*3*3*5.  A quarter note is already 1/(2*2) of a whole note, so that 720 ticks per
quarter can exact represent 64th notes as well as 1/8 triplets and quintuplets down to 1/16ths.
A value of ticks per quarter that results
in higher resolution that your MIDI playing software's timing offers is probably not meaningful.
@node Beat Size
@section Beat Size
@cindex Beat Size
The beat size is the musical ratio for the size of a beat.  In 6/8 meter, for example,
you could specify a beat size of 3/8.
@node Meter
@section Meter
@cindex Meter
@emph{meter} is written as you give it, but with separate number of beats and beat size,
into the @command{textmidi} file as a TIME_SIGNATURE command, along with ticks per quarter.
@node Tempo per Beat
@section Tempo per Beat
@cindex Tempo per Beat
The tempo per beat is the metronomic tempo of beats per minute for the beat size specified in the
@emph{beat size} field.  It is converted into a tempo of quarters per minute for the 
@command{textmidicgm} language output because that is how MIDI (1) uses tempo.
@command{textmidicgm} will compute rhythms based on beat size, meter, and tempo per beat,
but must write the equivalent tempo for a quarter note (for example, a meter of 60 for a 
beat size of 3/8 and with 1440 ticks/quarter will be written as a command TEMPO 90 1440
because MIDI tempo is always for a quarter note.
@node Melodic Probabilities
@section Melodic Probabilities
@cindex Melodic Probabilities
Melodic Probabilities are cumulative probabilities that apply only when a voice is in 
walking mode: they determine how often a voice moves up, or moves down, repeats a note, or
is resting.  A random variable used to select melodic movement 
varies in (0..<1.0).  When the random variable is:

@itemize
@item Below the "Down" probability, the voice will move down a step in the scale; when ;
@item At or above Down and below the Same probability, it will repeat the previous key;
@item At or above the Up probability, it will step up the scale.
@item At or above the Up probability, it will be silent.
@end itemize
Because these are cumulative probabilities, the following inequalities must hold:
0.0 <= Down <= Same <= Up <= 1.0.
If you don't want the voice to drift off down or up, then the probabilities for up and down should be
equal, but by differences:  (Up - Same) == (Same - Down).
These probabilities apply only if a voice is in walking mode.
@node Arrangements
@section Arrangements
@cindex Arrangements
Arrangements, if set, can change the priority of voices under the texture curve.
Each arrangement algorithm permutes the voice priorities in a different way.
Some of the algorithms do not produce all possible permutations, but others do.
These algorithms are described in the documentation for textmidicgm.
The settable items for Arrangements are:
@itemize
@item Algorithm
@itemize
@item Undefined
@item Identity
@item LexicographicForward
@item LexicographicBackward
@item RotateRight
@item RotateLeft
@item Reverse
@item SwapPairs
@item Skip
@item Shuffle
@item Heaps
@end itemize
@item Period
The period of time before going to the next permutation.
@end itemize
@node Scale Transpose and From Keyboard
@section Scale Transpose and From Keyboard
@cindex Scale Transpose and From Keyboard
Scales can be entered the following ways:
@itemize
@item Loaded from a form file
@item Set from the scale menu selections
@item Loaded from the keyboard window, by using the "From Keyboard" push button.
@end itemize
Once a scale has been loaded, it may be transposed by using the transpose spin button.
Note that if the scale loaded from a file was already transposed, then that version
of the scale will be the 
transposition of zero (0) in the Musical Form window for that scale.

Pushing the From Keyboard button will copy the scale that is set in the keyboard window
to be the scale in the musical form.

@node Pitch Form
@section Pitch Form
@cindex Pitch Form
The Form curves are the core concept of the textmidicgm model for musical form.
The curves are always sinusoidal (wave-like), but they are biased to sit above zero
and range from 0 to 1.  Pitch, Rhythm, and Dynamic curves have two sinusoids: mean and range.
The controls for each sinusoid include a period (in seconds) and a phase slider in radians.
There are two * pi radians (about 6.28) in a full circle.  The slider ranges from -pi to +pi.
For example, to get 90 degrees, set the slider about 3/4 of the way across between 0 and +pi.
The mean sinusoid is roughly the average or center value of the parameter (in which parameter refers to 
pitch, rhythm, and dynamic) and the sinusoid for range gives the range from low value to high
value.  Only a range sinusoid is used for texture.
The seven sinusoids are all all independent in phase and period.
After adjusting form curve values, you should select the Redraw item on the Form Plot window's menu
to see how you have changed the form.
The result of these curves is to cause the music generated by textmidicgm to change in 
character over time.  Ordinarily the periods used are around 120 to 360 seconds (2 to 6 minutes).
However, to make a parameter's mean or range stay static, merely make the period very long, such as
1000000 seconds.
Unless a voice is in walking mode,
the Pitch mean curve generally causes the pitches played to be higher when the curve is higher
and lower when the curve is lowe; the Pitch range curve causes a wider range of of notes
in the scale when the curve is higher and fewer (even just repeating a pitch).
In walking mode, a voice ignores the pitch curves and follows the melodic probabilities on
how to walk up and down.

@node Rhythm Form
@section Rhythm Form
@cindex Rhythm Form
A high rhythm mean curve generally tells textmidicgm to make longer duration (slower) note events.
When the rhythm mean curve is at a low point in the wave, it tends to make shorter durations (faster notes).
A high rhythm range curve tends to make a wider range of durations and sound more syncopated, even
with a pulse-per-second set; a low rhythm range curve tends to make more monotonous and repetitive
durations.
@node Dynamic Form
@section Dynamic Form
@cindex Dynamic Form
A high dynamic mean curve generally tells textmidicgm to make louder note events.
When the dynamic mean curve is at a low point in the wave, it tends to make quieter notes.
A high dynamic range curve tends to make a wider range of loudnesses and sound more natural;
a low dynamic range curve tends to make more evenly loud notes.

@node Texture Form
@section Texture Form
@cindex Texture Form
A high texture range curve makes more voices playe (a larger complement);
a low texture range curve makes fewer voices play.  
As the texture curve rises, the voices are added in voice number order.
To suggest a solist, the solo voice should probably be in voice 0 position in the voice window.

@node Instrumental Voices Window
@chapter Instrumental Voices Window
@cindex Instrumental Voices Window
@image{VoiceWindow,2.9in,2.6in,Voice Window,png}
@menu
* Number of Voices::
* Voice::
* Low Pitch::
* High Pitch::
* Channel::
* Program::
* Walking::
* Pan::
* Follow/Leader::
* Interval Type/Interval::
* Follower Delay::
* Follower Retrograde::
* Follower Inversion::
@end menu
The Instrumental Voices Window has several items.
@node Number of Voices
@section Number of Voices
@cindex Number of Voices
The number of voices is the total number of voices that can play when the form's texture curve
is high.  This model of musical form is basically counterpuntal and made of solo voices.
There is no real limit for number of voices, but the form editor only offers 23 voices.

@node Voice
@section Voice
@cindex Voice
Voice is the index (in 0..Number of Voices - 1) of the voice to be currently edited in the voice window.

@node Low Pitch
@section Low Pitch
@cindex Low Pitch
The low pitch is the low pitch for the voice.  If the Form Pitch curve goes below this low pitch, then
the low pitch will be played.  This can be monotonous; textmidicgm has an option on the command that
trims the scale to the range for all the instruments together to help with this, but this is not a 
perfect fix.
The @quotedblleft{}From Program@quotedblright{} push button will set the Low Pitch suitable for the
patch.  The instrument ranges were taken from textbooks or from en.wikipedia.org.

@multitable @columnfractions .4 .20 .20
@headitem Patch @tab Low Pitch @tab High Pitch
@item Acoustic_Grand_Piano @tab A0 @tab C8
@item Bright_Acoustic_Piano @tab A0 @tab C8
@item Electric_Grand_Piano @tab E1 @tab E7
@item Honky-tonk_Piano @tab A0 @tab C8
@item Electric_Piano_1(Fender_Rhodes) @tab A0 @tab C8
@item Electric_Piano_2(DX-7_EP) @tab A0 @tab C8
@item Harpsichord @tab F1 @tab F6
@item Clavi @tab F1 @tab F6
@item Chromatic Percussion
@item Celesta @tab C4 @tab C8
@item Glockenspiel @tab F5 @tab C8
@item Music_Box @tab F6 @tab C8
@item Vibraphone @tab F3 @tab F6
@item Marimba @tab C2 @tab C7
@item Xylophone @tab C3 @tab C7
@item Tubular @tab 15 @tab C4 G5
@item Dulcimer @tab C3 @tab C5
@item Organ @tab @tab
@item Drawbar_Organ @tab A0 @tab C8
@item Percussive_Organ @tab A0 @tab C8
@item Rock_Organ @tab A0 @tab C8
@item Church_Organ @tab A0 @tab C8
@item Reed_Organ @tab C2 @tab C6
@item Accordion @tab E1 @tab D6
@item Harmonica @tab C3 @tab G5
@item Tango @tab 24 @tab E1 D6
@item Guitar @tab @tab
@item Acoustic_Guitar_(nylon) @tab E3 @tab D6
@item Acoustic_Guitar_(steel) @tab E3 @tab D6
@item Electric_Guitar_(jazz) @tab E3 @tab D6
@item Electric_Guitar_(clean) @tab E3 @tab D6
@item Electric_Guitar_(muted) @tab E3 @tab D6
@item Overdriven_Guitar @tab E3 @tab D6
@item Distortion_Guitar @tab E3 @tab D6
@item Guitar_Harmonics @tab E4 @tab D7
@item Bass @tab @tab
@item Acoustic_Bass @tab E1 @tab E4
@item Electric_Bass_(finger) @tab E1 @tab E4
@item Electric_Bass_(pick) @tab E1 @tab E4
@item Fretless_Bass @tab E1 @tab E4
@item Slap_Bass_1 @tab E1 @tab E4
@item Slap_Bass_2 @tab E1 @tab E4
@item Synth_Bass_1 @tab E1 @tab E4
@item Synth_Bass_2 @tab E1 @tab E4
@item Strings @tab @tab
@item Violin @tab G3 @tab C7
@item Viola @tab C3 @tab D7
@item Cello @tab C2 @tab A5
@item Contrabass @tab E1 @tab G4
@item Tremolo_Strings @tab E1 @tab C7
@item Pizzicato_Strings @tab E1 @tab C7
@item Orchestral_Harp @tab B0 @tab G#7
@item Timpani @tab C2 @tab D4
@item Ensemble @tab @tab
@item String_Ensemble_1 @tab C0 @tab C8
@item String_Ensemble_2 @tab C0 @tab C8
@item Synth_Strings_1 @tab C0 @tab C8
@item Synth_Strings_2 @tab C0 @tab C8
@item Choir_Aahs @tab D2 @tab C6
@item Voice_Oohs @tab D2 @tab C6
@item Synth_Voice @tab D2 @tab C6
@item Orchestra_Hit @tab C0 @tab C8
@item Brass @tab @tab
@item Trumpet @tab F#3 @tab C6
@item Trombone @tab C2 @tab C5
@item Tuba @tab Eb2 @tab A4
@item Muted_Trumpet @tab F#3 @tab C6
@item French_Horn @tab C2 @tab C6
@item Brass_Section @tab C2 @tab C6
@item Synth_Brass_1 @tab C2 @tab C6
@item Synth_Brass_2 @tab C2 @tab C6
@item Reed @tab @tab
@item Soprano_Sax @tab Ab3 @tab Eb6
@item Alto_Sax @tab Db3 @tab Ab5
@item Tenor_Sax @tab Ab2 @tab Eb5
@item Baritone_Sax @tab Db2 @tab Ab4
@item Oboe @tab Bb3 @tab G6
@item English_Horn @tab E3 @tab A5
@item Bassoon @tab Bb1 @tab E5
@item Clarinet @tab D3 @tab Bb6
@item Pipe @tab @tab
@item Piccolo @tab D5 @tab C8
@item Flute @tab C4 @tab C7
@item Recorder @tab C-1 @tab G9
@item Pan_Flute @tab C-1 @tab G9
@item Blown_bottle @tab C-1 @tab G9
@item Shakuhachi @tab C-1 @tab G9
@item Whistle @tab C-1 @tab G9
@item Ocarina @tab C-1 @tab G9
@item Synth Lead @tab @tab
@item Lead_1_(square) @tab C0 @tab C8
@item Lead_2_(sawtooth) @tab C0 @tab C8
@item Lead_3_(calliope) @tab C0 @tab C8
@item Lead_4_(chiff) @tab C0 @tab C8
@item Lead_5_(charang) @tab C0 @tab C8
@item Lead_6_(voice) @tab C0 @tab C8
@item Lead_7_(fifths) @tab C0 @tab C8
@item Lead_8_(bass_+_lead) @tab C0 @tab C8
@item Synth Pad @tab @tab
@item Pad_1_(new_age) @tab C0 @tab C8
@item Pad_2_(warm) @tab C0 @tab C8
@item Pad_3_(polysynth) @tab C0 @tab C8
@item Pad_4_(choir) @tab C2 @tab G5
@item Pad_5_(bowed) @tab C0 @tab C8
@item Pad_6_(metallic) @tab C0 @tab C8
@item Pad_7_(halo) @tab C0 @tab C8
@item Pad_8_(sweep) @tab C0 @tab C8
@item Synth Effects @tab @tab
@item FX_1_(rain) @tab C0 @tab C8
@item FX_2_(soundtrack) @tab C0 @tab C8
@item FX_3_(crystal) @tab C0 @tab C8
@item FX_4_(atmosphere) @tab C0 @tab C8
@item FX_5_(brightness) @tab C0 @tab C8
@item FX_6_(goblins) @tab C0 @tab C8
@item FX_7_(echoes) @tab C0 @tab C8
@item FX_8_(sci-fi) @tab C0 @tab C8
@item Ethnic @tab @tab
@item Sitar @tab C2 @tab C6
@item Banjo @tab D3 @tab C6
@item Shamisen @tab E3 @tab C6
@item Koto @tab C2 @tab C6
@item Kalimba @tab G3 @tab G6
@item Bag @tab 110 @tab C3 C6
@item Fiddle @tab G3 @tab C7
@item Shanai @tab Bb3 @tab G6
@item Percussive @tab @tab
@item Tinkle @tab C-1 @tab G9
@item Agogô @tab C-1 @tab G9
@item Steel_Drums @tab C-1 @tab G9
@item Woodblock @tab C-1 @tab G9
@item Taiko_Drum @tab C-1 @tab G9
@item Melodic_Tom @tab C-1 @tab G9
@item Synth_Drum @tab C-1 @tab G9
@item Reverse_Cymbal @tab C-1 @tab G9
@item Sound Effects @tab @tab
@item Guitar_Fret_Noise @tab C-1 @tab G9
@item Breath_Noise @tab C-1 @tab G9
@item Seashore @tab C-1 @tab G9
@item Bird_Tweet @tab C-1 @tab G9
@item Telephone_Ring @tab C-1 @tab G9
@item Helicopter @tab C-1 @tab G9
@item Applause @tab C-1 @tab G9
@item Gunshot @tab C-1 @tab G9
@end multitable

@node High Pitch
@section High Pitch
@cindex High Pitch
The high pitch is the high pitch for the voice.  If the Form Pitch curve goes above this high pitch, then
the high pitch will be played.  This can be monotonous; textmidicgm has an option on the command that
trims the scale to the range for all the instruments together to help with this, but this is not a 
perfect fix.
The @quotedblleft{}From Program@quotedblright{} push button will set the High Pitch suitable for the
patch.

@node Channel
@section Channel
@cindex Channel
The channel is the MIDI Channel (1..16) for the voice.

@node Program
@section Program
@cindex Program
The Program is the MIDI program name from General MIDI used for the current voice.

@node Walking
@section Walking
@cindex Walking
The walking value sets the probability of a voice being in walking mode, note to note.  In walking mode, a voice ignores
the Form Pitch curve and follows the Melodic Probabilities.
The value ranges from 0.0 (random melody) to 1.0 (walking up and down the scale).  
A value between 0.0 and 1.0 represents the probability of the voice being in walking mode, note to note.
This makes it possible for a single voice to randomly be in either walking or random (jumpy) mode.

@node Pan
@section Pan
@cindex Pan
Pan is the MIDI stereo pan for the voice.

@node Follow/Leader
@section Follow/Leader
@cindex Follow/Leader
The Follower/Leader feature permits you to tell a voice to ignore the Form curves altogether, and
instead to follow another voice.  Set the follow button to make a voice follow another.
Set the Leader to the number of the voice to follow.  Select the interval type of following: scaler or chromatic.
Scaler intervals will count steps up in the scale (down for a negative interval)
being used to select the interval of following;
chromatic intervals will count by 1's up (down for a negative interval) in a chromatic scale to find the
follower's pitch.

@node Interval Type/Interval
@section Interval Type/Interval
@cindex Interval Type/Interval
The follower's Interval Type defines whether the follower stays in the scale for the form, or
if it follows on a chromatic interval.  If the interval type is scaler, then the interval is the
number of steps up or down the scale that the follower appears.  If the interval type is chromatic,
then the follower will be "Interval" number of chromatic steps away from the voice it is following.

@node Follower Delay
@section Follower Delay
@cindex Follower Delay
The follower's Delay creates a canon effect in that it 
delays the start of the following voice for the duration given as an ordinary
rational number.  It can be set to 1/4 for a quarter note, or 13/17, or
4/1 or 4 for four whole notes delay and so on.  It interprets 4 as four whole notes and not
as a quarter note the way @command{textmidi} does in LAZY mode.

@node Follower Inversion
@section Follower Inversion
@cindex Follower Inversion
The follower can be an inversion of the leader voice, for the entire duration 
of the piece.  Transposition interval still applies.
The selection of either chromatic or scalar following also applies.

@node Follower Retrograde
@section Follower Retrograde
@cindex Follower Retrograde
The follower will be a retrograde (that is, a backwards copy) of the leader voice, 
for the entire duration of the piece.  Transposition interval still applies.
The selection of either chromatic or scalar following also applies.

@node Form Plot Window
@chapter Form Plot Window
@cindex Form Plot Window
@image{FormPlotWindow,4.7in,3.2in,Form Plot Window,png}
The Form Plot window has a menu.
@menu
* Open::
* Save::
* Redraw::
* Save Postscript::
* About::
* Quit::
@end menu
The Form Plot Window shows the sinusoidsal curves that act to change the mean and range of pitch,
rhythm (duration), dynamic (loudness) and the complement (the number of instruments playing).
A vertical line is drawn at each minute of time from the beginning.
The Form Plot Window menu has several items.
@node Open
@section Open
@cindex Open
The Open menu allows you to load a boost::serialization (cf. boost.org) XML archive
form file.  All of the values of the form file will be distributed throughout the
user interface and the plot redrawn.
@node Save
@section Save
@cindex Save
The Save menu allows you to save an XML 
form file.  All of the values of the form in the user interface of
TextMidiFormEdit.py will be written out to the file.
The XML form file is readable by @command{textmidicgm} using the --xmlform option.

@node Redraw
@section Redraw
@cindex Redraw
The form plot is redrawn; this is called for if the form curves are 
changed in the Musical Form window.

@node Save Postscript
@section Save Postscript
@cindex Save Postscript
The Save Postscript menu item will save a Postscript image of the Form Plot window.

@node About
@section About
@cindex About
The About item puts up a window with information about the program.

@node Quit
@section Quit
@cindex Quit
The Quit menu item will exit the program.  The window close decoration will also
do this.  Any work done but unsaved is lost; you are not prompted to save work.

@node Keyboard Window
@chapter Keyboard Window
@cindex Keyboard Window
@image{KeyboardWindow,6in,0.77in,Keyboard Window,png}

The Keyboard Window has a keyboard in which individual keys can be clicked, and also several buttons.
The keyboard presents 128 keys, all of the keys supported by MIDI (C-1 to G9).  Middle-C is outlined
in a thicker line than other keys.  Any key can be clicked
to toggle whether it is to be included in a scale.
When a key is included in a scale it is drawn with a stipple in blue (if a white key)
or red (if a black key).  Keys that are not in the scale
are white if they are white keys and black if they are black keys.
The keyboard will reflect selection of scale made in the Musical Form window, and the scale
in the keyboard window can be copied into the form by clicking on the "From Keyboard" button
in the Musical Form window.  The keyboard does not affect the scale in the Form until you click
"From Keyboard".
Clicking on a key toggles its inclusion in the scale.  If you click on a selected key,
it is removed from the scale; if the key is not in the scale, then clicking on it 
adds it to the scale.
Any arbitrary combination of the 128 keys can be clicked to create a scale.
To create a scale that repeats each octave, just click the unique keys for one octave, then hit the
"Octave Repeat" push button.
@menu
* Clear::
* All::
* Complement::
* Octave Repeat::
@end menu
@node Clear
@section Clear
@cindex Clear
Clear the scale.

@node All
@section All
@cindex All
Set all of the keys, that is, the full chromatic MIDI scale.

@node Complement
@section Complement
@cindex Complement
Set the scale to select notes not in the scale and remove
notes that were in the scale.
For example, select a Diatonic scale in the Musical Form window; this will appear in the keyboard as C Major.
Then push the Complement push button on the Keyboard window 
to select the missing notes instead, and the result will be the black
keys only, which is a form of pentatonic scale.

@node Octave Repeat
@section Octave Repeat
@cindex Octave Repeat
Any notes set in the keyboard are repeated per octave throughout the full scale.

@node GNU Free Documentation License
@chapter GNU Free Documentation License
Version 1.3, 3 November 2008
Copyright @copyright{} 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
https://fsf.org/
Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
@section PREAMBLE
The purpose of this License is to make a manual, textbook, or other functional and
useful document free in the sense of freedom: to assure everyone the effective freedom
to copy and redistribute it, with or without modifying it, either commercially or non-
commercially. Secondarily, this License preserves for the author and publisher a way
to get credit for their work, while not being considered responsible for modifications
made by others.
This License is a kind of “copyleft”, which means that derivative works of the document
must themselves be free in the same sense. It complements the GNU General Public
License, which is a copyleft license designed for free software.
We have designed this License in order to use it for manuals for free software, because
free software needs free documentation: a free program should come with manuals
providing the same freedoms that the software does. But this License is not limited to
software manuals; it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book. We recommend this License principally for
works whose purpose is instruction or reference.
@section APPLICABILITY AND DEFINITIONS
This License applies to any manual or other work, in any medium, that contains a
notice placed by the copyright holder saying it can be distributed under the terms
of this License. Such a notice grants a world-wide, royalty-free license, unlimited in
duration, to use that work under the conditions stated herein.
The “Document”,
below, refers to any such manual or work. Any member of the public is a licensee, and
is addressed as “you”. You accept the license if you copy, modify or distribute the work
in a way requiring permission under copyright law.
A “Modified Version” of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or translated into
another language.
A “Secondary Section” is a named appendix or a front-matter section of the Document
that deals exclusively with the relationship of the publishers or authors of the Document
to the Document’s overall subject (or to related matters) and contains nothing that
could fall directly within that overall subject. (Thus, if the Document is in part a
textbook of mathematics, a Secondary Section may not explain any mathematics.) The
relationship could be a matter of historical connection with the subject or with related
matters, or of legal, commercial, philosophical, ethical or political position regarding
them.
The “Invariant Sections” are certain Secondary Sections whose titles are designated, as
being those of Invariant Sections, in the notice that says that the Document is released
under this License. If a section does not fit the above definition of Secondary then it is
not allowed to be designated as Invariant. The Document may contain zero Invariant
Sections. If the Document does not identify any Invariant Sections then there are none.
The “Cover Texts” are certain short passages of text that are listed, as Front-Cover
Texts or Back-Cover Texts, in the notice that says that the Document is released under
this License. A Front-Cover Text may be at most 5 words, and a Back-Cover Text may
be at most 25 words.
A “Transparent” copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is suitable for
revising the document straightforwardly with generic text editors or (for images com-
posed of pixels) generic paint programs or (for drawings) some widely available drawing
editor, and that is suitable for input to text formatters or for automatic translation to
a variety of formats suitable for input to text formatters. A copy made in an otherwise
Transparent file format whose markup, or absence of markup, has been arranged to
thwart or discourage subsequent modification by readers is not Transparent. An image
format is not Transparent if used for any substantial amount of text. A copy that is
not “Transparent” is called “Opaque”.
Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTEX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or pro-
cessing tools are not generally available, and the machine-generated HTML, PostScript
or PDF produced by some word processors for output purposes only.
The “Title Page” means, for a printed book, the title page itself, plus such following
pages as are needed to hold, legibly, the material this License requires to appear in the
title page. For works in formats which do not have any title page as such, “Title Page”
means the text near the most prominent appearance of the work’s title, preceding the
beginning of the body of the text.
The “publisher” means any person or entity that distributes copies of the Document
to the public.
A section “Entitled XYZ” means a named subunit of the Document whose title either
is precisely XYZ or contains XYZ in parentheses following text that translates XYZ in
another language. (Here XYZ stands for a specific section name mentioned below, such
as “Acknowledgements”, “Dedications”, “Endorsements”, or “History”.) To “Preserve
the Title” of such a section when you modify the Document means that it remains a
section “Entitled XYZ” according to this definition.
The Document may include Warranty Disclaimers next to the notice which states that
this License applies to the Document. These Warranty Disclaimers are considered to
be included by reference in this License, but only as regards disclaiming warranties:
any other implication that these Warranty Disclaimers may have is void and has no
effect on the meaning of this License.
@section VERBATIM COPYING
You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the license
notice saying this License applies to the Document are reproduced in all copies, and
that you add no other conditions whatsoever to those of this License. You may not use
technical measures to obstruct or control the reading or further copying of the copies
you make or distribute. However, you may accept compensation in exchange for copies.
If you distribute a large enough number of copies you must also follow the conditions
in section 3.
You may also lend copies, under the same conditions stated above, and you may publicly
display copies.
@section COPYING IN QUANTITY
If you publish printed copies (or copies in media that commonly have printed covers) of
the Document, numbering more than 100, and the Document’s license notice requires
Cover Texts, you must enclose the copies in covers that carry, clearly and legibly, all
these Cover Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover. Both covers must also clearly and legibly identify you as the publisher
of these copies. The front cover must present the full title with all words of the title
equally prominent and visible. You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in other
respects.
If the required texts for either cover are too voluminous to fit legibly, you should put
the first ones listed (as many as fit reasonably) on the actual cover, and continue the
rest onto adjacent pages.
If you publish or distribute Opaque copies of the Document numbering more than 100,
you must either include a machine-readable Transparent copy along with each Opaque
copy, or state in or with each Opaque copy a computer-network location from which
the general network-using public has access to download using public-standard network
protocols a complete Transparent copy of the Document, free of added material. If
you use the latter option, you must take reasonably prudent steps, when you begin
distribution of Opaque copies in quantity, to ensure that this Transparent copy will
remain thus accessible at the stated location until at least one year after the last time
you distribute an Opaque copy (directly or through your agents or retailers) of that
edition to the public.
It is requested, but not required, that you contact the authors of the Document well
before redistributing any large number of copies, to give them a chance to provide you
with an updated version of the Document.
@section MODIFICATIONS
You may copy and distribute a Modified Version of the Document under the conditions
of sections 2 and 3 above, provided that you release the Modified Version under precisely
this License, with the Modified Version filling the role of the Document, thus licensing
distribution and modification of the Modified Version to whoever possesses a copy of
it. In addition, you must do these things in the Modified Version:
A. Use in the Title Page (and on the covers, if any) a title distinct from that of the
Document, and from those of previous versions (which should, if there were any,
be listed in the History section of the Document). You may use the same title as
a previous version if the original publisher of that version gives permission.
B. List on the Title Page, as authors, one or more persons or entities responsible for
authorship of the modifications in the Modified Version, together with at least five
of the principal authors of the Document (all of its principal authors, if it has fewer
than five), unless they release you from this requirement.
C. State on the Title page the name of the publisher of the Modified Version, as the
publisher.
D. Preserve all the copyright notices of the Document.
E. Add an appropriate copyright notice for your modifications adjacent to the other
copyright notices.
F. Include, immediately after the copyright notices, a license notice giving the public
permission to use the Modified Version under the terms of this License, in the form
shown in the Addendum below.
G. Preserve in that license notice the full lists of Invariant Sections and required Cover
Texts given in the Document’s license notice.
H. Include an unaltered copy of this License.
I. Preserve the section Entitled “History”, Preserve its Title, and add to it an item
stating at least the title, year, new authors, and publisher of the Modified Version
as given on the Title Page. If there is no section Entitled “History” in the Docu-
ment, create one stating the title, year, authors, and publisher of the Document
as given on its Title Page, then add an item describing the Modified Version as
stated in the previous sentence.
J. Preserve the network location, if any, given in the Document for public access to
a Transparent copy of the Document, and likewise the network locations given in
the Document for previous versions it was based on. These may be placed in the
“History” section. You may omit a network location for a work that was published
at least four years before the Document itself, or if the original publisher of the
version it refers to gives permission.
K. For any section Entitled “Acknowledgements” or “Dedications”, Preserve the Title
of the section, and preserve in the section all the substance and tone of each of the
contributor acknowledgements and/or dedications given therein.
L. Preserve all the Invariant Sections of the Document, unaltered in their text and
in their titles. Section numbers or the equivalent are not considered part of the
section titles.
M. Delete any section Entitled “Endorsements”. Such a section may not be included
in the Modified Version.
N. Do not retitle any existing section to be Entitled “Endorsements” or to conflict in
title with any Invariant Section.
O. Preserve any Warranty Disclaimers.
If the Modified Version includes new front-matter sections or appendices that qualify
as Secondary Sections and contain no material copied from the Document, you may at
your option designate some or all of these sections as invariant. To do this, add their
titles to the list of Invariant Sections in the Modified Version’s license notice. These
titles must be distinct from any other section titles.
You may add a section Entitled “Endorsements”, provided it contains nothing but
endorsements of your Modified Version by various parties—for example, statements of
peer review or that the text has been approved by an organization as the authoritative
definition of a standard.
You may add a passage of up to five words as a Front-Cover Text, and a passage of up
to 25 words as a Back-Cover Text, to the end of the list of Cover Texts in the Modified
Version. Only one passage of Front-Cover Text and one of Back-Cover Text may be
added by (or through arrangements made by) any one entity. If the Document already
includes a cover text for the same cover, previously added by you or by arrangement
made by the same entity you are acting on behalf of, you may not add another; but
you may replace the old one, on explicit permission from the previous publisher that
added the old one.
The author(s) and publisher(s) of the Document do not by this License give permission
to use their names for publicity for or to assert or imply endorsement of any Modified
Version.
@section COMBINING DOCUMENTS
You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that you
include in the combination all of the Invariant Sections of all of the original documents,
unmodified, and list them all as Invariant Sections of your combined work in its license
notice, and that you preserve all their Warranty Disclaimers.
The combined work need only contain one copy of this License, and multiple identical
Invariant Sections may be replaced with a single copy. If there are multiple Invariant
Sections with the same name but different contents, make the title of each such section
unique by adding at the end of it, in parentheses, the name of the original author or
publisher of that section if known, or else a unique number. Make the same adjustment
to the section titles in the list of Invariant Sections in the license notice of the combined
work.
In the combination, you must combine any sections Entitled “History” in the vari-
ous original documents, forming one section Entitled “History”; likewise combine any
sections Entitled “Acknowledgements”, and any sections Entitled “Dedications”. You
must delete all sections Entitled “Endorsements.”
@section COLLECTIONS OF DOCUMENTS
You may make a collection consisting of the Document and other documents released
under this License, and replace the individual copies of this License in the various
documents with a single copy that is included in the collection, provided that you
follow the rules of this License for verbatim copying of each of the documents in all
other respects.
You may extract a single document from such a collection, and distribute it individu-
ally under this License, provided you insert a copy of this License into the extracted
document, and follow this License in all other respects regarding verbatim copying of
that document.
@section AGGREGATION WITH INDEPENDENT WORKS
A compilation of the Document or its derivatives with other separate and independent
documents or works, in or on a volume of a storage or distribution medium, is called
an “aggregate” if the copyright resulting from the compilation is not used to limit the
legal rights of the compilation’s users beyond what the individual works permit. When
the Document is included in an aggregate, this License does not apply to the other
works in the aggregate which are not themselves derivative works of the Document.
If the Cover Text requirement of section 3 is applicable to these copies of the Document,
then if the Document is less than one half of the entire aggregate, the Document’s Cover
Texts may be placed on covers that bracket the Document within the aggregate, or the
electronic equivalent of covers if the Document is in electronic form. Otherwise they
must appear on printed covers that bracket the whole aggregate.
@section TRANSLATION
Translation is considered a kind of modification, so you may distribute translations
of the Document under the terms of section 4.
Replacing Invariant Sections with
translations requires special permission from their copyright holders, but you may
include translations of some or all Invariant Sections in addition to the original versions
of these Invariant Sections. You may include a translation of this License, and all the
license notices in the Document, and any Warranty Disclaimers, provided that you
also include the original English version of this License and the original versions of
those notices and disclaimers. In case of a disagreement between the translation and
the original version of this License or a notice or disclaimer, the original version will
prevail.
If a section in the Document is Entitled “Acknowledgements”, “Dedications”, or “His-
tory”, the requirement (section 4) to Preserve its Title (section 1) will typically require
changing the actual title.
@section TERMINATION
You may not copy, modify, sublicense, or distribute the Document except as expressly
provided under this License. Any attempt otherwise to copy, modify, sublicense, or
distribute it is void, and will automatically terminate your rights under this License.
However, if you cease all violation of this License, then your license from a particular
copyright holder is reinstated (a) provisionally, unless and until the copyright holder
explicitly and finally terminates your license, and (b) permanently, if the copyright
holder fails to notify you of the violation by some reasonable means prior to 60 days
after the cessation.
Moreover, your license from a particular copyright holder is reinstated permanently if
the copyright holder notifies you of the violation by some reasonable means, this is the
first time you have received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after your receipt of the
notice.
Termination of your rights under this section does not terminate the licenses of parties
who have received copies or rights from you under this License. If your rights have
been terminated and not permanently reinstated, receipt of a copy of some or all of the
same material does not give you any rights to use it.
@section FUTURE REVISIONS OF THIS LICENSE
The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in spirit
to the present version, but may differ in detail to address new problems or concerns.
See https://www.gnu.org/copyleft/.
Each version of the License is given a distinguishing version number. If the Document
specifies that a particular numbered version of this License “or any later version”
applies to it, you have the option of following the terms and conditions either of that
specified version or of any later version that has been published (not as a draft) by
the Free Software Foundation. If the Document does not specify a version number of
this License, you may choose any version ever published (not as a draft) by the Free
Software Foundation. If the Document specifies that a proxy can decide which future
versions of this License can be used, that proxy’s public statement of acceptance of a
version permanently authorizes you to choose that version for the Document.
@section RELICENSING
“Massive Multiauthor Collaboration Site” (or “MMC Site”) means any World Wide
Web server that publishes copyrightable works and also provides prominent facilities
for anybody to edit those works. A public wiki that anybody can edit is an example of
such a server. A “Massive Multiauthor Collaboration” (or “MMC”) contained in the
site means any set of copyrightable works thus published on the MMC site.
“CC-BY-SA” means the Creative Commons Attribution-Share Alike 3.0 license pub-
lished by Creative Commons Corporation, a not-for-profit corporation with a principal
place of business in San Francisco, California, as well as future copyleft versions of that
license published by that same organization.
“Incorporate” means to publish or republish a Document, in whole or in part, as part
of another Document.
An MMC is “eligible for relicensing” if it is licensed under this License, and if all works
that were first published under this License somewhere other than this MMC, and
subsequently incorporated in whole or in part into the MMC, (1) had no cover texts
or invariant sections, and (2) were thus incorporated prior to November 1, 2008.
The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC is
eligible for relicensing.
@section How to use this License for your documents
To use this License in a document you have written, include a copy of the License in the
document and put the following copyright and license notices just after the title page:
Copyright (C)
year
your name.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover
Texts.
A copy of the license is included in the section entitled ``GNU
Free Documentation License''.
If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts, replace the
“with. . . Texts.” line with this:
with the Invariant Sections being list their titles, with
the Front-Cover Texts being list, and with the Back-Cover Texts
being list.
If you have Invariant Sections without Cover Texts, or some other combination of the
three, merge those two alternatives to suit the situation.
If your document contains nontrivial examples of program code, we recommend releasing
these examples in parallel under your choice of free software license, such as the GNU
General Public License, to permit their use in free software.


@node Bibliography
@chapter Bibliography
@cindex Bibliography

@node Concept Index
@chapter Concept Index
@printindex cp

@bye
